/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Library Items */
        get: operations["list_library_items_library_items_get"];
        put?: never;
        /** Import Library Item */
        post: operations["import_library_item_library_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Library Item */
        get: operations["get_library_item_library_items__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/items/{item_id}/editions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Editions */
        get: operations["list_editions_library_items__item_id__editions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{source_id}/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse Document */
        post: operations["parse_document_documents__source_id__parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{source_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Source Documents */
        get: operations["list_source_documents_sources__source_id__documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document Blocks */
        get: operations["get_document_blocks_documents__document_id__blocks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document Chapters */
        get: operations["get_document_chapters_documents__document_id__chapters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/editions/{edition_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Edition */
        get: operations["get_edition_editions__edition_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/editions/{edition_id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Audio */
        post: operations["create_audio_editions__edition_id__audio_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audio-renders/{render_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Audio Render */
        get: operations["get_audio_render_audio_renders__render_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/editions/{edition_id}/audio-renders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audio Renders */
        get: operations["list_audio_renders_editions__edition_id__audio_renders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audio-parts/{part_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Audio Part */
        post: operations["retry_audio_part_audio_parts__part_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audio-parts/{part_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Audio Part */
        get: operations["stream_audio_part_audio_parts__part_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AudioChunkView */
        AudioChunkView: {
            /** Id */
            id: string;
            /** Position */
            position: number;
            /** Status */
            status: string;
            /** Attempt Count */
            attempt_count: number;
            /** Duration Ms */
            duration_ms: number | null;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
        };
        /** AudioPartView */
        AudioPartView: {
            /** Id */
            id: string;
            /** Position */
            position: number;
            /** Batch Index */
            batch_index: number;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /** Duration Ms */
            duration_ms: number | null;
            /** Retry Count */
            retry_count: number;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /** Chunks */
            chunks: components["schemas"]["AudioChunkView"][];
        };
        /** AudioRenderView */
        AudioRenderView: {
            /** Id */
            id: string;
            /** Edition Id */
            edition_id: string;
            /** Status */
            status: string;
            /** Voice */
            voice: string;
            /** Rate */
            rate: string;
            /** Pitch */
            pitch: string;
            /** Provider */
            provider: string;
            /** Batch Size */
            batch_size: number;
            /** Batch Count */
            batch_count: number;
            /** Next Batch Index */
            next_batch_index: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Parts */
            parts: components["schemas"]["AudioPartView"][];
        };
        /** Body_import_library_item_library_items_post */
        Body_import_library_item_library_items_post: {
            /** Title */
            title: string;
            /**
             * Content Type
             * @default unknown
             * @enum {string}
             */
            content_type: "novel" | "technical" | "article" | "unknown";
            /** Author */
            author?: string | null;
            /** File */
            file?: string | null;
            /** Pasted Text */
            pasted_text?: string | null;
        };
        /** ContentBlockView */
        ContentBlockView: {
            /** Id */
            id: string;
            /** Parsed Document Id */
            parsed_document_id: string;
            /** Parent Id */
            parent_id: string | null;
            /** Position */
            position: number;
            /** Block Type */
            block_type: string;
            /** Text */
            text: string;
            /** Source Start */
            source_start: number | null;
            /** Source End */
            source_end: number | null;
            /** Block Metadata */
            block_metadata: {
                [key: string]: unknown;
            };
        };
        /** CreateAudioRequest */
        CreateAudioRequest: {
            /**
             * Voice
             * @default zh-CN-XiaoxiaoNeural
             */
            voice: string;
            /**
             * Rate
             * @default +0%
             */
            rate: string;
            /**
             * Pitch
             * @default +0Hz
             */
            pitch: string;
        };
        /** CreateAudioResponse */
        CreateAudioResponse: {
            render: components["schemas"]["AudioRenderView"];
            /** Run Id */
            run_id: string;
        };
        /** EditionBlockView */
        EditionBlockView: {
            /** Id */
            id: string;
            /** Position */
            position: number;
            /** Kind */
            kind: string;
            /** Text */
            text: string;
            /** Source Block Ids */
            source_block_ids: string[];
            /** Section Title */
            section_title: string | null;
            /** Audio Status */
            audio_status: string;
        };
        /** EditionView */
        EditionView: {
            /** Id */
            id: string;
            /** Library Item Id */
            library_item_id: string;
            /** Parsed Document Id */
            parsed_document_id: string;
            /** Edition Type */
            edition_type: string;
            /** Title */
            title: string;
            /** Full Text */
            full_text: string;
            /** Script Version */
            script_version: string;
            /** Status */
            status: string;
            /** Blocks */
            blocks: components["schemas"]["EditionBlockView"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportResponse */
        ImportResponse: {
            item: components["schemas"]["LibraryItemView"];
            source: components["schemas"]["SourceDocumentView"];
            /** Run Id */
            run_id: string;
        };
        /** LibraryItemDetail */
        LibraryItemDetail: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Author */
            author: string | null;
            /** Content Type */
            content_type: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Sources */
            sources: components["schemas"]["SourceDocumentView"][];
        };
        /** LibraryItemView */
        LibraryItemView: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Author */
            author: string | null;
            /** Content Type */
            content_type: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ParsedDocumentDetail */
        ParsedDocumentDetail: {
            /** Id */
            id: string;
            /** Source Document Id */
            source_document_id: string;
            /** Parser Version */
            parser_version: string;
            /** Document Type */
            document_type: string;
            /** Language */
            language: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Blocks */
            blocks: components["schemas"]["ContentBlockView"][];
        };
        /** ParsedDocumentView */
        ParsedDocumentView: {
            /** Id */
            id: string;
            /** Source Document Id */
            source_document_id: string;
            /** Parser Version */
            parser_version: string;
            /** Document Type */
            document_type: string;
            /** Language */
            language: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PipelineRunView */
        PipelineRunView: {
            /** Id */
            id: string;
            /** Run Type */
            run_type: string;
            /** Root Entity Type */
            root_entity_type: string;
            /** Root Entity Id */
            root_entity_id: string;
            /** Status */
            status: string;
            /** Progress */
            progress: number;
            /** Nodes */
            nodes: components["schemas"]["TaskNodeView"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SourceDocumentView */
        SourceDocumentView: {
            /** Id */
            id: string;
            /** Library Item Id */
            library_item_id: string;
            /** Source Type */
            source_type: string;
            /** Original Filename */
            original_filename: string | null;
            /** Mime Type */
            mime_type: string;
            /** Content Hash */
            content_hash: string;
            /** Encoding */
            encoding: string | null;
            /** Parse Status */
            parse_status: string;
        };
        /** TaskNodeView */
        TaskNodeView: {
            /** Id */
            id: string;
            /** Parent Id */
            parent_id: string | null;
            /** Node Type */
            node_type: string;
            /** Status */
            status: string;
            /** Progress */
            progress: number;
            /** Attempt Count */
            attempt_count: number;
            /** Max Attempts */
            max_attempts: number;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /** Started At */
            started_at: string | null;
            /** Heartbeat At */
            heartbeat_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_library_items_library_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryItemView"][];
                };
            };
        };
    };
    import_library_item_library_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_library_item_library_items_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_library_item_library_items__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryItemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_editions_library_items__item_id__editions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditionView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_document_documents__source_id__parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineRunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParsedDocumentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_source_documents_sources__source_id__documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParsedDocumentView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_blocks_documents__document_id__blocks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentBlockView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_chapters_documents__document_id__chapters_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentBlockView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_edition_editions__edition_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                edition_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_audio_editions__edition_id__audio_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                edition_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAudioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAudioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audio_render_audio_renders__render_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                render_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudioRenderView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audio_renders_editions__edition_id__audio_renders_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                edition_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudioRenderView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_audio_part_audio_parts__part_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                part_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_audio_part_audio_parts__part_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                part_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineRunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
