"""create_phase_one_schema

Revision ID: p1_initial
Revises:
Create Date: 2026-08-14 18:11:08.118762
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "p1_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("mime_type", sa.String(length=160), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_assets_storage_key")),
    )
    op.create_index(op.f("ix_assets_content_hash"), "assets", ["content_hash"], unique=False)
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_type", sa.String(length=32), nullable=False),
        sa.Column("root_entity_type", sa.String(length=32), nullable=False),
        sa.Column("root_entity_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_runs")),
    )
    op.create_index(
        op.f("ix_pipeline_runs_root_entity_id"), "pipeline_runs", ["root_entity_id"], unique=False
    )
    op.create_table(
        "library_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("author", sa.String(length=300), nullable=True),
        sa.Column("content_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("cover_asset_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cover_asset_id"], ["assets.id"], name=op.f("fk_library_items_cover_asset_id_assets")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_library_items")),
    )
    op.create_table(
        "task_nodes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column("node_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("output_asset_id", sa.String(length=36), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["output_asset_id"], ["assets.id"], name=op.f("fk_task_nodes_output_asset_id_assets")
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["task_nodes.id"],
            name=op.f("fk_task_nodes_parent_id_task_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["pipeline_runs.id"],
            name=op.f("fk_task_nodes_run_id_pipeline_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_nodes")),
        sa.UniqueConstraint("run_id", "idempotency_key", name=op.f("uq_task_nodes_run_id")),
    )
    op.create_table(
        "tts_cache",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("audio_asset_id", sa.String(length=36), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_version", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["audio_asset_id"],
            ["assets.id"],
            name=op.f("fk_tts_cache_audio_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tts_cache")),
        sa.UniqueConstraint("cache_key", name=op.f("uq_tts_cache_cache_key")),
    )
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("library_item_id", sa.String(length=36), nullable=False),
        sa.Column("goal", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("plan", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["library_item_id"],
            ["library_items.id"],
            name=op.f("fk_agent_runs_library_item_id_library_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    op.create_table(
        "source_documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("library_item_id", sa.String(length=36), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("original_filename", sa.String(length=500), nullable=True),
        sa.Column("mime_type", sa.String(length=160), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("cleaned_asset_id", sa.String(length=36), nullable=True),
        sa.Column("encoding", sa.String(length=80), nullable=True),
        sa.Column("parse_status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["assets.id"], name=op.f("fk_source_documents_asset_id_assets")
        ),
        sa.ForeignKeyConstraint(
            ["cleaned_asset_id"],
            ["assets.id"],
            name=op.f("fk_source_documents_cleaned_asset_id_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["library_item_id"],
            ["library_items.id"],
            name=op.f("fk_source_documents_library_item_id_library_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_documents")),
        sa.UniqueConstraint(
            "library_item_id", "content_hash", name=op.f("uq_source_documents_library_item_id")
        ),
    )
    op.create_table(
        "parsed_documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_document_id", sa.String(length=36), nullable=False),
        sa.Column("parser_version", sa.String(length=40), nullable=False),
        sa.Column("document_type", sa.String(length=32), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("report_asset_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_asset_id"],
            ["assets.id"],
            name=op.f("fk_parsed_documents_report_asset_id_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_documents.id"],
            name=op.f("fk_parsed_documents_source_document_id_source_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parsed_documents")),
        sa.UniqueConstraint(
            "source_document_id",
            "parser_version",
            name=op.f("uq_parsed_documents_source_document_id"),
        ),
    )
    op.create_table(
        "content_blocks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("parsed_document_id", sa.String(length=36), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("block_type", sa.String(length=32), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("asset_id", sa.String(length=36), nullable=True),
        sa.Column("source_start", sa.Integer(), nullable=True),
        sa.Column("source_end", sa.Integer(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("parser_version", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["assets.id"], name=op.f("fk_content_blocks_asset_id_assets")
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["content_blocks.id"],
            name=op.f("fk_content_blocks_parent_id_content_blocks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parsed_document_id"],
            ["parsed_documents.id"],
            name=op.f("fk_content_blocks_parsed_document_id_parsed_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_blocks")),
        sa.UniqueConstraint(
            "parsed_document_id", "position", name=op.f("uq_content_blocks_parsed_document_id")
        ),
    )
    op.create_table(
        "editions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("library_item_id", sa.String(length=36), nullable=False),
        sa.Column("parsed_document_id", sa.String(length=36), nullable=False),
        sa.Column("agent_run_id", sa.String(length=36), nullable=True),
        sa.Column("edition_type", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("full_text", sa.Text(), nullable=False),
        sa.Column("script_version", sa.String(length=40), nullable=False),
        sa.Column("source_references", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_run_id"], ["agent_runs.id"], name=op.f("fk_editions_agent_run_id_agent_runs")
        ),
        sa.ForeignKeyConstraint(
            ["library_item_id"],
            ["library_items.id"],
            name=op.f("fk_editions_library_item_id_library_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parsed_document_id"],
            ["parsed_documents.id"],
            name=op.f("fk_editions_parsed_document_id_parsed_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_editions")),
    )
    op.create_table(
        "audio_renders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("edition_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("voice", sa.String(length=120), nullable=False),
        sa.Column("rate", sa.String(length=16), nullable=False),
        sa.Column("pitch", sa.String(length=16), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_version", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["edition_id"],
            ["editions.id"],
            name=op.f("fk_audio_renders_edition_id_editions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audio_renders")),
    )
    op.create_table(
        "edition_blocks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("edition_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("source_block_ids", sa.JSON(), nullable=False),
        sa.Column("section_title", sa.String(length=500), nullable=True),
        sa.Column("audio_status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["edition_id"],
            ["editions.id"],
            name=op.f("fk_edition_blocks_edition_id_editions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_edition_blocks")),
        sa.UniqueConstraint("edition_id", "position", name=op.f("uq_edition_blocks_edition_id")),
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("agent_run_id", sa.String(length=36), nullable=False),
        sa.Column("content_block_id", sa.String(length=36), nullable=False),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("analysis_version", sa.String(length=40), nullable=False),
        sa.Column("inference", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_evidence_agent_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["content_block_id"],
            ["content_blocks.id"],
            name=op.f("fk_evidence_content_block_id_content_blocks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
    )
    op.create_table(
        "audio_parts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("audio_render_id", sa.String(length=36), nullable=False),
        sa.Column("edition_block_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("audio_asset_id", sa.String(length=36), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["audio_asset_id"], ["assets.id"], name=op.f("fk_audio_parts_audio_asset_id_assets")
        ),
        sa.ForeignKeyConstraint(
            ["audio_render_id"],
            ["audio_renders.id"],
            name=op.f("fk_audio_parts_audio_render_id_audio_renders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["edition_block_id"],
            ["edition_blocks.id"],
            name=op.f("fk_audio_parts_edition_block_id_edition_blocks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audio_parts")),
        sa.UniqueConstraint(
            "audio_render_id", "position", name=op.f("uq_audio_parts_audio_render_id")
        ),
    )
    op.create_table(
        "audio_chunks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("audio_part_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("source_block_ids", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("audio_asset_id", sa.String(length=36), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["audio_asset_id"], ["assets.id"], name=op.f("fk_audio_chunks_audio_asset_id_assets")
        ),
        sa.ForeignKeyConstraint(
            ["audio_part_id"],
            ["audio_parts.id"],
            name=op.f("fk_audio_chunks_audio_part_id_audio_parts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audio_chunks")),
        sa.UniqueConstraint(
            "audio_part_id", "position", name=op.f("uq_audio_chunks_audio_part_id")
        ),
    )
    op.create_index(op.f("ix_audio_chunks_cache_key"), "audio_chunks", ["cache_key"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audio_chunks_cache_key"), table_name="audio_chunks")
    op.drop_table("audio_chunks")
    op.drop_table("audio_parts")
    op.drop_table("evidence")
    op.drop_table("edition_blocks")
    op.drop_table("audio_renders")
    op.drop_table("editions")
    op.drop_table("content_blocks")
    op.drop_table("parsed_documents")
    op.drop_table("source_documents")
    op.drop_table("agent_runs")
    op.drop_table("tts_cache")
    op.drop_table("task_nodes")
    op.drop_table("library_items")
    op.drop_index(op.f("ix_pipeline_runs_root_entity_id"), table_name="pipeline_runs")
    op.drop_table("pipeline_runs")
    op.drop_index(op.f("ix_assets_content_hash"), table_name="assets")
    op.drop_table("assets")
    # ### end Alembic commands ###
