"""add_audio_batches

Revision ID: p2_audio_batches
Revises: p1_initial
Create Date: 2026-08-15 13:09:26.177862
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "p2_audio_batches"
down_revision: str | None = "p1_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "audio_parts", sa.Column("batch_index", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "audio_renders", sa.Column("batch_size", sa.Integer(), server_default="3", nullable=False)
    )
    op.add_column(
        "audio_renders", sa.Column("batch_count", sa.Integer(), server_default="1", nullable=False)
    )
    op.add_column(
        "audio_renders",
        sa.Column("next_batch_index", sa.Integer(), server_default="1", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("audio_renders", "next_batch_index")
    op.drop_column("audio_renders", "batch_count")
    op.drop_column("audio_renders", "batch_size")
    op.drop_column("audio_parts", "batch_index")
    # ### end Alembic commands ###
